version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test -v ./...
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: ./script/release
workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
          - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
